### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qiota** [mishalhossin/Discord-AI-Chatbot#103]
I can't send everything, but here's the final error code.
Threw on Repl.it

> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('162.159.128.233', 443)]

**Comment by mishalhossin** [comment]
> I can't send everything, but here's the final error code. Threw on Repl.it
> 
> > aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('162.159.128.233', 443)]

1. Check your internet connection
2. Check for firewall or proxy restrictions and  ensure that it is not blocking the connection to discord.com on port 443. Contact your network administrator if necessary
3. Temporarily disable antivirus or security software because Sometimes, antivirus or security software can interfere with network connections
4. If possible, try connecting to Discord from a different network or location
