### ISSUE TITLE
ratelimit and unauthorized errors after about 15 messages

### ISSUE THREAD

**Issue by ninsaccplayzyt** [mishalhossin/Discord-AI-Chatbot#260]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/95270582/59a15076-bb18-4b4e-8ca9-732c537565be)

**Comment by charliesh4rk** [comment]
happened with me as well, i tried a day later and it still was not working

**Comment by ninsaccplayzyt** [comment]
yeah it just seems to be stuck with an unauthorized error and rate limits no matter how long you wait

**Comment by Roboxkin** [comment]
I don't know for sure, but I had a similar problem
Try changing the delay from 8 to 10
It worked for me

![Screenshot](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/39112555/54acc845-9e40-46b5-bb79-58329f4f6931)

**Comment by L7NEG** [comment]
fr you are right 

> yeah it just seems to be stuck with an unauthorized error and rate limits no matter how long you wait

**Comment by RocketSmash9000** [comment]
I'm here just to say that it's happening on my machine as well

**Comment by RocketSmash9000** [comment]
It's been 2 days since the issue was created. Maybe the support team has a real life and can't work on this project often

**Comment by Roboxkin** [comment]
> Прошло 2 дня с момента создания проблемы. Возможно, у команды поддержки есть реальная жизнь, и они не могут часто работать над этим проектом.

And look at the other problems, the first problem has been open for 3 weeks already.

**Comment by L7NEG** [comment]
fr @mishalhossin sorry for ping

**Comment by kipperc** [comment]
stuck for me that way now too :(

**Comment by Roboxkin** [comment]
After I ran test.py
```
gpt-3.5-turbo failed
gpt-4 failed
```
I think that there are no restrictions, as far as I remember this was stated a few days ago, all this is a lie.
Nobody helps with problems here, from the developers. I don't think this project should be used.
Therefore, it worked from the very beginning, and then stopped due to restrictions. After the ogies have been achieved, you and I have this oshika.
In general, I delete this project from myself and blacklist it.
something like this
